import {
  deleteSettingIfValue,
  getSetting,
  listSettingsByPrefix,
  mutateSetting,
} from "@agent-native/core/settings";
import { resolveAccess } from "@agent-native/core/sharing";
import { track, type TrackingSource } from "@agent-native/core/tracking";

/**
 * A home-prompt deck is generated by an ordinary chat run, so no action owns
 * its completion and the editor tab that used to report it is often closed by
 * the time the run ends. The turn that lands a generation deck's first slide is
 * recorded here and reported once, server-side, when the turn finishes: a run
 * that errored or was stopped reports nothing, and a run that hands its turn
 * to a continuation run waits for it.
 */
export interface GenerationFirstOutput {
  deckId: string;
  generationAttemptId: string;
  targetSlideCount: number | null;
}

const MAX_TRACKED_TURNS = 500;
const firstOutputsByTurn = new Map<string, GenerationFirstOutput[]>();

// A continuation run keeps its turn id but may run in another process, so a
// turn that hands off moves its markers to shared storage; a row only outlives
// its turn when the turn never finishes, and then it expires.
const PENDING_KEY_PREFIX = "slides-generation-pending:";
const PENDING_TTL_MS = 24 * 60 * 60 * 1000;
// How long one worker may hold a turn's markers while it reports them. A
// worker that dies mid-report leaves a lease that lapses, and a later run of
// the turn reports again: at-least-once, never silently dropped.
const FINALIZING_LEASE_MS = 2 * 60 * 1000;

interface PendingRow {
  outputs: GenerationFirstOutput[];
  expiresAt: number;
  finalizing?: { owner: string; until: number };
}

export function noteGenerationFirstOutput(
  turnKey: string | undefined,
  output: GenerationFirstOutput,
): void {
  if (!turnKey) return;
  if (
    !firstOutputsByTurn.has(turnKey) &&
    firstOutputsByTurn.size >= MAX_TRACKED_TURNS
  ) {
    const oldest = firstOutputsByTurn.keys().next().value;
    if (oldest !== undefined) firstOutputsByTurn.delete(oldest);
  }
  const outputs = firstOutputsByTurn.get(turnKey) ?? [];
  if (outputs.some((entry) => entry.deckId === output.deckId)) return;
  firstOutputsByTurn.set(turnKey, [...outputs, output]);
}

function mergeOutputs(
  ...lists: readonly GenerationFirstOutput[][]
): GenerationFirstOutput[] {
  const byDeck = new Map<string, GenerationFirstOutput>();
  for (const output of lists.flat()) {
    if (!byDeck.has(output.deckId)) byDeck.set(output.deckId, output);
  }
  return [...byDeck.values()];
}

function isFirstOutput(value: unknown): value is GenerationFirstOutput {
  const output = value as Partial<GenerationFirstOutput> | null;
  return (
    typeof output?.deckId === "string" &&
    typeof output.generationAttemptId === "string" &&
    (output.targetSlideCount === null ||
      typeof output.targetSlideCount === "number")
  );
}

/** The stored row, or null when there is none or it has expired. */
function parsePendingRow(
  turnKey: string,
  stored: Record<string, unknown> | null,
): PendingRow | null {
  if (!stored) return null;
  if (typeof stored.expiresAt !== "number") {
    throw new Error(`Malformed pending generation marker for turn ${turnKey}.`);
  }
  if (stored.expiresAt <= Date.now()) return null;
  const finalizing = stored.finalizing as PendingRow["finalizing"] | undefined;
  if (!Array.isArray(stored.outputs) || !stored.outputs.every(isFirstOutput)) {
    throw new Error(`Malformed pending generation marker for turn ${turnKey}.`);
  }
  return {
    outputs: stored.outputs,
    expiresAt: stored.expiresAt,
    ...(finalizing ? { finalizing } : {}),
  };
}

async function storePendingOutputs(
  turnKey: string,
  outputs: GenerationFirstOutput[],
): Promise<void> {
  const key = `${PENDING_KEY_PREFIX}${turnKey}`;
  await mutateSetting(key, (current) => {
    const row = parsePendingRow(turnKey, current);
    return {
      ...row,
      outputs: mergeOutputs(row?.outputs ?? [], outputs),
      expiresAt: Date.now() + PENDING_TTL_MS,
    };
  });
  // Written first, so a failed sweep cannot lose the marker. A row is removed
  // only while it is still the expired value that was listed.
  for (const { key: staleKey, value } of await listSettingsByPrefix(
    PENDING_KEY_PREFIX,
  )) {
    if (typeof value.expiresAt === "number" && value.expiresAt <= Date.now()) {
      await deleteSettingIfValue(staleKey, value);
    }
  }
}

/**
 * Takes the turn's markers for reporting, atomically: of two workers that
 * finish the same turn, one gets them and the other gets null.
 */
async function claimFinalization(
  turnKey: string,
  local: GenerationFirstOutput[],
): Promise<{
  outputs: GenerationFirstOutput[];
  owner: string;
  held: Record<string, unknown>;
} | null> {
  const key = `${PENDING_KEY_PREFIX}${turnKey}`;
  const stored = await getSetting(key);
  if (local.length === 0 && !parsePendingRow(turnKey, stored)) {
    // Nothing to report; an expired row is cleared while it is still the one read.
    if (stored) await deleteSettingIfValue(key, stored);
    return null;
  }
  const owner = crypto.randomUUID();
  let outputs: GenerationFirstOutput[] = [];
  let claimed = false;
  const held = await mutateSetting(key, (current) => {
    const row = parsePendingRow(turnKey, current);
    const lease = row?.finalizing;
    outputs = mergeOutputs(row?.outputs ?? [], local);
    claimed = !(lease && lease.until > Date.now() && lease.owner !== owner);
    if (!claimed && current) return current;
    return {
      outputs,
      expiresAt: Date.now() + PENDING_TTL_MS,
      finalizing: { owner, until: Date.now() + FINALIZING_LEASE_MS },
    };
  });
  return claimed ? { outputs, owner, held } : null;
}

/** Gives the markers back after a failed read, unless the lease moved on. */
async function releaseFinalization(
  turnKey: string,
  owner: string,
): Promise<void> {
  const key = `${PENDING_KEY_PREFIX}${turnKey}`;
  if (!(await getSetting(key))) return;
  await mutateSetting(key, (current) => {
    const row = parsePendingRow(turnKey, current);
    if (!current || !row || row.finalizing?.owner !== owner) {
      return current ?? {};
    }
    const { finalizing: _released, ...rest } = row;
    return rest;
  });
}

export async function trackGenerationCompletedForRun(
  run: { runId: string; turnId?: string; threadId?: string; status: string },
  outcome: { turnContinues: boolean },
  readSlideCount: (deckId: string) => Promise<number | null>,
  source?: TrackingSource,
): Promise<void> {
  const turnKey = run.turnId || run.runId;
  const local = firstOutputsByTurn.get(turnKey) ?? [];
  if (outcome.turnContinues && run.status !== "aborted") {
    if (local.length > 0) {
      await storePendingOutputs(turnKey, local);
      firstOutputsByTurn.delete(turnKey);
    }
    return;
  }
  const claim = await claimFinalization(turnKey, local);
  if (!claim) return;
  const { outputs, owner, held } = claim;
  firstOutputsByTurn.delete(turnKey);
  const key = `${PENDING_KEY_PREFIX}${turnKey}`;
  if (run.status !== "completed") {
    await deleteSettingIfValue(key, held);
    return;
  }
  // Every read happens before anything is reported, so a failed read gives the
  // markers back for a later run of the turn and nothing is reported twice.
  const counts = new Map<string, number | null>();
  try {
    for (const output of outputs) {
      counts.set(output.deckId, await readSlideCount(output.deckId));
    }
  } catch (error) {
    await releaseFinalization(turnKey, owner);
    throw error;
  }
  for (const output of outputs) {
    const slideCount = counts.get(output.deckId) ?? null;
    if (slideCount === null || slideCount === 0) continue;
    track(
      "generation_completed",
      {
        app_name: "slides",
        template_name: "slides",
        generation_attempt_id: output.generationAttemptId,
        output_id: output.deckId,
        output_type: "deck",
        slide_count: slideCount,
        ...(output.targetSlideCount !== null
          ? { target_slide_count: output.targetSlideCount }
          : {}),
        outcome:
          output.targetSlideCount === null ||
          slideCount >= output.targetSlideCount
            ? "completed"
            : "partial",
        run_id: run.runId,
        ...(run.threadId ? { thread_id: run.threadId } : {}),
        source: "agent_run",
      },
      source,
    );
  }
  // Dropped only after every report was handed off.
  await deleteSettingIfValue(key, held);
}

/**
 * A deck deleted or unshared before its run ended resolves to null; any other
 * failure rejects, so an unreadable deck is never mistaken for a gone one.
 */
export async function readGeneratedDeckSlideCount(
  deckId: string,
): Promise<number | null> {
  const access = await resolveAccess("deck", deckId);
  if (!access) return null;
  const data = JSON.parse((access.resource as { data: string }).data) as {
    slides?: unknown;
  };
  return Array.isArray(data.slides) ? data.slides.length : 0;
}
