import {
  table,
  text,
  integer,
  ownableColumns,
  createSharesTable,
} from "@agent-native/core/db/schema";
import { boolean } from "drizzle-orm/pg-core";

import {
  PLAN_AUTHORS,
  PLAN_COMMENT_KINDS,
  PLAN_COMMENT_RESOLUTION_TARGETS,
  PLAN_COMMENT_STATUSES,
  PLAN_KINDS,
  PLAN_REPORT_REASONS,
  PLAN_REPORT_STATUSES,
  PLAN_SECTION_TYPES,
  PLAN_SOURCES,
  PLAN_STATUSES,
} from "../../shared/types.js";

export const plans = table("plans", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  brief: text("brief").notNull(),
  kind: text("kind", { enum: PLAN_KINDS }).notNull().default("plan"),
  status: text("status", { enum: PLAN_STATUSES }).notNull().default("draft"),
  source: text("source", { enum: PLAN_SOURCES }).notNull().default("manual"),
  repoPath: text("repo_path"),
  currentFocus: text("current_focus"),
  html: text("html"),
  markdown: text("markdown"),
  content: text("content"),
  hostedPlanId: text("hosted_plan_id"),
  hostedPlanUrl: text("hosted_plan_url"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  approvedAt: text("approved_at"),
  // LLM usage + derived cost for the run that produced this row. Nullable —
  // only populated for `kind="recap"` recaps generated by the PR Visual Recap
  // workflow (Claude Code / Codex). Column names mirror core's token_usage /
  // UsageRecord; cost is stored in centicents (1/100¢) to match it exactly.
  usageAgent: text("usage_agent"),
  usageModel: text("usage_model"),
  usageInputTokens: integer("usage_input_tokens"),
  usageOutputTokens: integer("usage_output_tokens"),
  usageCacheReadTokens: integer("usage_cache_read_tokens"),
  usageCacheWriteTokens: integer("usage_cache_write_tokens"),
  usageCostCentsX100: integer("usage_cost_cents_x100"),
  usageCostSource: text("usage_cost_source"),
  usageRecordedAt: text("usage_recorded_at"),
  sourceUrl: text("source_url"),
  sourceType: text("source_type"),
  sourceRepo: text("source_repo"),
  sourcePrNumber: integer("source_pr_number"),
  sourcePrState: text("source_pr_state"),
  sourcePrMergedAt: text("source_pr_merged_at"),
  sourceAuthorEmail: text("source_author_email"),
  sourceAuthorName: text("source_author_name"),
  sourceAuthorLogin: text("source_author_login"),
  recapIdempotencyKey: text("recap_idempotency_key"),
  // Edition (`kind="edition"`) window identity. `editionDateKey` is the
  // idempotency key a scheduled run derives from its own timezone, and the
  // partial unique index on it is what stops a retry publishing twice.
  editionDateKey: text("edition_date_key"),
  editionWindowStart: text("edition_window_start"),
  editionWindowEnd: text("edition_window_end"),
  editionTimezone: text("edition_timezone"),
  editionCoverageJson: text("edition_coverage_json"),
  // Sequential issue number, assigned per owner/org at publish time. Makes an
  // edition a citable object ("No. 214") rather than just a date.
  editionIssueNumber: integer("edition_issue_number"),
  /**
   * Which recurring edition this issue belongs to — `daily`, `internal-weekly`,
   * `design-daily`. Part of an edition's identity alongside the window, so two
   * differently-scoped editions covering the same day coexist instead of one
   * silently replacing the other. NULL reads as `daily` for rows written before
   * series existed.
   */
  editionSeries: text("edition_series"),
  /**
   * The day's through-line, written once per edition: what connects the
   * stories, and what to read sceptically. This is the editorial voice the
   * stories themselves cannot carry.
   */
  editionNotes: text("edition_notes"),
  deletedAt: text("deleted_at"),
  deletedBy: text("deleted_by"),
  ...ownableColumns(),
});

export const planSections = table("plan_sections", {
  id: text("id").primaryKey(),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  type: text("type", { enum: PLAN_SECTION_TYPES }).notNull().default("custom"),
  title: text("title").notNull(),
  body: text("body").notNull().default(""),
  html: text("html"),
  order: integer("sort_order").notNull().default(0),
  createdBy: text("created_by", { enum: PLAN_AUTHORS })
    .notNull()
    .default("agent"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const planComments = table("plan_comments", {
  id: text("id").primaryKey(),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  parentCommentId: text("parent_comment_id").references(() => planComments.id),
  sectionId: text("section_id").references(() => planSections.id),
  kind: text("kind", { enum: PLAN_COMMENT_KINDS }).notNull().default("comment"),
  status: text("status", { enum: PLAN_COMMENT_STATUSES })
    .notNull()
    .default("open"),
  anchor: text("anchor"),
  message: text("message").notNull(),
  createdBy: text("created_by", { enum: PLAN_AUTHORS })
    .notNull()
    .default("human"),
  authorEmail: text("author_email"),
  authorName: text("author_name"),
  resolutionTarget: text("resolution_target", {
    enum: PLAN_COMMENT_RESOLUTION_TARGETS,
  }),
  mentionsJson: text("mentions_json"),
  resolvedBy: text("resolved_by"),
  resolvedAt: text("resolved_at"),
  consumedAt: text("consumed_at"),
  deletedAt: text("deleted_at"),
  deletedBy: text("deleted_by"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const planEvents = table("plan_events", {
  id: text("id").primaryKey(),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  type: text("type").notNull(),
  message: text("message").notNull(),
  payload: text("payload"),
  createdBy: text("created_by", { enum: PLAN_AUTHORS })
    .notNull()
    .default("agent"),
  createdAt: text("created_at").notNull(),
});

export const planReports = table("plan_reports", {
  id: text("id").primaryKey(),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  reason: text("reason", { enum: PLAN_REPORT_REASONS }).notNull(),
  details: text("details"),
  status: text("status", { enum: PLAN_REPORT_STATUSES })
    .notNull()
    .default("open"),
  reporterEmail: text("reporter_email"),
  reporterName: text("reporter_name"),
  pageUrl: text("page_url"),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const planVersions = table("plan_versions", {
  id: text("id").primaryKey(),
  ownerEmail: text("owner_email").notNull().default("local@localhost"),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  title: text("title").notNull(),
  snapshotJson: text("snapshot_json").notNull(),
  changeLabel: text("change_label"),
  createdBy: text("created_by", { enum: PLAN_AUTHORS })
    .notNull()
    .default("agent"),
  createdAt: text("created_at").notNull(),
  chatContext: text("chat_context"),
  status: text("summary_status", { enum: PLAN_STATUSES }),
  source: text("summary_source", { enum: PLAN_SOURCES }),
  blockCount: integer("block_count"),
  sectionCount: integer("section_count"),
  hasCanvas: boolean("has_canvas"),
  hasPrototype: boolean("has_prototype"),
  previewText: text("preview_text"),
});

/**
 * One story per row for an `edition` plan, mirroring how `plan_sections` and
 * `plan_comments` hang off a plan. Stories are generated, never hand-edited, so
 * they deliberately stay out of `plans.content` and the MDX round-trip.
 *
 * `recapsJson` holds `EditionStoryRecapRef[]` — the recaps the story was written
 * from, so a headline can link back to `/recaps/:id`. Its per-PR diff stats are
 * nullable on purpose: a missing stat must stay distinguishable from zero.
 */
export const planEditionStories = table("plan_edition_stories", {
  id: text("id").primaryKey(),
  editionId: text("edition_id")
    .notNull()
    .references(() => plans.id),
  storyId: text("story_id").notNull(),
  order: integer("sort_order").notNull().default(0),
  isLead: boolean("is_lead").notNull().default(false),
  headline: text("headline").notNull(),
  dek: text("dek").notNull().default(""),
  tagsJson: text("tags_json"),
  recapsJson: text("recaps_json").notNull(),
  /**
   * `EditionStoryCohort[]` — the sub-themes a story spans, each carrying its
   * own PR count and aggregate diff. This is what a story shows instead of one
   * row per pull request: a reader gets 2-4 named cohorts, not 11 citations.
   */
  cohortsJson: text("cohorts_json"),
  whatShipped: text("what_shipped"),
  why: text("why"),
  howItWorks: text("how_it_works"),
  createdAt: text("created_at").notNull(),
});

export const planShares = createSharesTable("plan_shares");

export const planGuestMints = table("plan_guest_mints", {
  id: text("id").primaryKey(),
  ipHash: text("ip_hash").notNull(),
  createdAt: text("created_at").notNull(),
});

export const planAssets = table("plan_assets", {
  id: text("id").primaryKey(),
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id),
  filename: text("filename").notNull(),
  mimeType: text("mime_type").notNull(),
  data: text("data").notNull(),
  byteSize: integer("byte_size").notNull(),
  createdAt: text("created_at").notNull(),
});
